algorithm: 'carefl'  # in {'CAReFl', 'LRHyv', 'RECI', 'ANM'} OR in {'CAReFl', 'gp', 'linear'}

data:
  pair_id: 0
  remove_outliers: false
  scale: true
  verbose: true


# only relevant for flows
flow:
  architecture: 'CL'
  net_class: 'MLP'  # in {'MLP', 'ARMLP', 'MLP4'}.lower()
  nl: [1, 3]
  nh: 5
  batch_norm: false
  prior_dist: 'laplace'
  # for CL
  scale_base: true
  shift_base: true
  scale: true


training:
  epochs: 750
  verbose: false
  split: .8
  seed: 0
  batch_size: 128

optim:
  weight_decay: 0.000
  optimizer: "Adam"
  lr: 0.001
  beta1: 0.9
  amsgrad: false
  scheduler: true


